# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0355885690cdb22d6bcfd1e4bf17f9ac9cb42c812886ea997842588d807aba1fbc5f62900312d059dc6a46eae50830401b877ae29c95a3bf6135fe6327dcf8f0

test:
  secret_key_base: f96f597bbbc57fd4f6661cbea42564762cf8d54279e8879d2d295f4f96818c26fcf0320202090dbc4fc73e8d2f8d173a8abf8476438dbb2b45d1cc7efdc177d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
